version: '3'

services:
  janus:
    image: gambit/janus-server
    ports:
    - 80:8088
  eureka:
    image: gambit/gambit-discovery-service
    ports:
    - 8761:8761
  config:
    image: gambit/gambit-configuration-service
    ports:
    - 8888:8888
  zuul:
    image: gambit/gambit-gateway-service
    ports:
    - 10000:10000
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka
  user:
    image: gambit/gambit-user-service
    ports:
    - 10001:10001
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka