version: '3'

services:
  janus:
    image: gambit/janus-server
    ports:
    - 80:8088
  eureka:
    image: gambit/gambit-discovery-service
    ports:
    - 8761:8761
    environment:
    - CONFIG_HOME=http://config:8888
  config:
    image: gambit/gambit-configuration-service
    ports:
    - 8888:8888
    environment:
    - CONFIG_REPO_URL=https://github.com/palagnajr/gambit-configuration.git
    - CONFIG_REPO_USERNAME=revature-github
    - CONFIG_REPO_PASSWORD=p4ssw0rd
  zuul:
    image: gambit/gambit-gateway-service
    ports:
    - 10000:10000
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka
    - CONFIG_HOME=http://config:8888
  user:
    image: gambit/gambit-user-service
    ports:
    - 10001:10001
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka
    - CONFIG_HOME=http://config:8888
    - KAFKA_URL=ec2-35-182-41-35.ca-central-1.compute.amazonaws.com:9092
  batch:
    image: gambit/gambit-batch-service
    ports:
    - 10002:10002
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka
    - CONFIG_HOME=http://config:8888
    - KAFKA_URL=ec2-35-182-41-35.ca-central-1.compute.amazonaws.com:9092
  skills:
    image: gambit/gambit-skills-service
    ports:
    - 10004:10004
    environment:
    - EUREKA_HOME=http://eureka:8761/eureka
    - CONFIG_HOME=http://config:8888
    - KAFKA_URL=ec2-35-182-41-35.ca-central-1.compute.amazonaws.com:9092